[tox]
envlist = lint, pytest, mypy
isolated_build = True

[testenv:lint]
deps =
    setuptools
    ruff
skip_install = true
commands = ruff check

[testenv]
deps =
    inform
    parametrize_from_file
    pytest
    pytest-cov
    pytest-subtests
    voluptuous

[testenv:pytest]
commands = py.test -vv --cov {posargs} --cov-branch --cov-report term-missing
